#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'newrelic_plugin'

require 'vmstat'

module DiskAgent

  class Agent < NewRelic::Plugin::Agent::Base
    agent_guid 'com.happyr.newrelic-disk-agent'
    agent_config_options :instance_name
    agent_version '0.0.1'
    agent_human_labels('Disk') { instance_name }

    def poll_cycle
      report_metric 'Disk/Free', 'Free',     Vmstat.snapshot.disk("/").free_bytes
      report_metric 'Disk/Used', 'Used',     Vmstat.snapshot.disk("/").used_bytes
      report_metric 'Disk/Total', 'Total', Vmstat.snapshot.disk("/").total_bytes
    end
  end

  NewRelic::Plugin::Config.config_file = File.dirname(__FILE__) + '/config/newrelic_plugin.yml'
  NewRelic::Plugin::Setup.install_agent :disk_agent, self

  NewRelic::Plugin::Run.setup_and_run

end
