#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'newrelic_plugin'

module DiskAgent

  class Agent < NewRelic::Plugin::Agent::Base
    agent_guid 'com.happyr.newrelic-disk-agent'
    agent_config_options :instance_name
    agent_version '0.0.1'
    agent_human_labels('Disk') { instance_name }

    def poll_cycle
      data = `df -h | tr -s ' ' | cut -d " " -f2,3,6`
      data.each_line do |line,index|
        if index>1
          parts = line.split
          report_metric 'Disk', parts[2], {"count"=>parts[1], "total"=>parts[0]}
        end
      end
    end
  end

  NewRelic::Plugin::Config.config_file = File.dirname(__FILE__) + '/config/newrelic_plugin.yml'
  NewRelic::Plugin::Setup.install_agent :disk_agents, DiskAgent

  NewRelic::Plugin::Run.setup_and_run

end
