#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'newrelic_plugin'

module DiskAgent

  class Agent < NewRelic::Plugin::Agent::Base
    agent_guid 'com.happyr.newrelic-disk-agent'
    agent_config_options :instance_name
    agent_version '0.2.0'
    agent_human_labels('Disks') { `hostname -f` }

    def poll_cycle
      data = `df -B 1 | tr -s ' ' | cut -d " " -f2,3,6 | sed 1d`
      data.each_line do |line|
        parts = line.split
        report_metric "MountPoint/"+parts[2], "bytes", parts[1]
        report_metric "MountPoint/"+parts[2], "Total", parts[0]
        report_metric "MountPoint/"+parts[2], "Percent", 100 * parts[1].to_f / parts[0].to_f
      end
    end
  end

  NewRelic::Plugin::Setup.install_agent :default, DiskAgent

  NewRelic::Plugin::Run.setup_and_run

end
